### ISSUE TITLE
Collaboration with another project

### ISSUE THREAD

**Issue by maikeru99** [shibbo/OdysseyDecomp#4]
First of all, thank you for your hard work in decompilation projects. Considering that [this project](https://github.com/MonsterDruide1/OdysseyDecomp) also exists, wouldn't be better to work together with him?

I'm just asking. Maybe you knew about this project before and there is a reason for another decompilation project for the same game.

**Comment by shibbo** [comment]
That decompilation is poorly organized and I just personally wanted to take a different approach to decompiling the game. Some information from that repository will be used here, so it's not useless
